Update README.md
uk-tre/community-management pull request #109
Opened 2024-05-21 08:51 UTC by Davsarper

PR that takes content for README from https://docs.google.com/document/d/1V8c_5QNGpz8d4s55DhL1vRatoz9FjU-MdLPFRxkwshs/edit#heading=h.x3jyd34dls23 into the README file in the CM repo

2024-06-18 09:54 UTC, balintstewart77 requested changes
could you please add my github handle to the list of community group co-chairs?

2024-07-09 09:01 UTC, Davsarper reviewed
add Balint handle, Pete (no handle), remove Hari

2024-07-09 09:01 UTC, Davsarper commented on README.md
> +- @harisood
```suggestion
```

2024-07-09 09:42 UTC, manics reviewed
I've added some suggested links

2024-07-09 09:42 UTC, manics commented on README.md
> +For more information about the community, please visit our website (insert link), and read through our governance docs (insert link).
```suggestion
For more information about the community, please visit our [website](https://www.uktre.org/), and read through our governance docs (insert link).
```

2026-07-15 00:07 UTC, merged