Initial write up of details to get from people
uk-tre/community-management pull request #37
Opened 2023-11-21 15:11 UTC by harisood

2023-11-21 15:14 UTC, harisood commented
Whoops I think I created this from the wrong branch, let's finalise and merge #26 and come back to this

2023-11-24 10:50 UTC, Davsarper requested changes

2023-11-24 10:50 UTC, Davsarper commented on events/templates/prompts_for_sessions.md
> +
```suggestion

Project workshops are focused discussions on a specific project, issue or challenge.
They are intended to serve as a collaborative work sessions where the community helps the presenter to move forward in their project. 

```

2023-11-24 10:50 UTC, Davsarper commented on events/templates/prompts_for_sessions.md
> +
I think that while we figure out an intuitive terminology we should add details about how we envision each type of breakout

2023-11-24 10:50 UTC, Davsarper commented on events/templates/prompts_for_sessions.md
> +*Please provide a short paragraph summarising your proposed session, including background and what you hope to cover. We'll share this on our website!*
```suggestion
*Please provide a short paragraph summarising your proposed session, including background and what you hope to cover. 
We'll share this on our website!*
```

2023-11-24 10:50 UTC, Davsarper commented on events/templates/prompts_for_sessions.md
> +
```suggestion

Breakout discussions are open talks around a topic.
They are open ended, and while we hope actions and collaboration arise from them, there is no specific output expected by the end of the session.

```

2023-11-27 18:10 UTC, harisood commented
@Davsarper nice edits! Please review again and if happy approve :)

2023-11-28 14:48 UTC, Davsarper approved these changes

2023-11-28 16:34 UTC, merged